# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl:

# Title of the Site
title: אגרובנק רוצה תכנון נכון
# Description of the Site
description: אגרובנק, מוותיקות בשכונות חולון, מתעוררת ודורשת עירוניות מאפשרת
# URL of Image of the Site
site-image: /agrobank/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /assets/images/cover.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: contact@agrobank.city
facebook_username: AgrobankRightPlan

# Google Analytics
google-analytics: G-8N7PQ78GY6


# Name of the Author
author-name: אגרובנק רוצה תכנון נכון
# URL for the Image of the Author
author-image: https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png
# 60 Words About the Author
author-about: קבוצת "אגרובנק רוצה תכנון נכון" נוסדה בשנת 2023 עי ידי חובבי עירוניות, תחבורה וקהילה במטרה אחת - להפוך את אגרובנק לשכונה שאנחנו רוצים לחיות בה 
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://www.facebook.com/AgrobankRightPlan

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
